import streamlit as st


def render_report_page(data):

    report = data.get("report", {})
    summary = data.get("summary", {})
    review = data.get("literature_review", {})

    report_title = report.get(
        "title",
        "Research Analysis Report"
    )

    generated_date = report.get(
        "generated_date",
        "Demo"
    )

    sections = report.get("sections", [])

    st.markdown(
        """
        <div class="hero-card">
            <div class="hero-kicker">RESEARCH OUTPUT</div>
            <h1>Research Report</h1>
            <p>
                Review, preview, and export the final research analysis
                generated by AutoResearch AI.
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.info(
        "📄 Demo Mode: This report currently uses sample/mock data. "
        "Final report generation will be connected to the backend later."
    )

    # ---------------------------------------------------------
    # REPORT HEADER
    # ---------------------------------------------------------

    st.markdown("## 📑 Report Overview")

    col1, col2 = st.columns(2)

    with col1:
        st.markdown(
            f"""
            <div class="info-card">
                <h3>Report Title</h3>
                <p>{report_title}</p>
            </div>
            """,
            unsafe_allow_html=True
        )

    with col2:
        st.markdown(
            f"""
            <div class="info-card">
                <h3>Generated Date</h3>
                <p>{generated_date}</p>
            </div>
            """,
            unsafe_allow_html=True
        )

    # ---------------------------------------------------------
    # RESEARCH SUMMARY
    # ---------------------------------------------------------

    st.markdown("## 📊 Research Summary")

    summary_col1, summary_col2, summary_col3 = st.columns(3)

    with summary_col1:
        st.metric(
            "Papers",
            summary.get("papers_found", 0)
        )

    with summary_col2:
        st.metric(
            "Citations",
            summary.get("citations", 0)
        )

    with summary_col3:
        st.metric(
            "Research Gaps",
            summary.get("research_gaps", 0)
        )

    # ---------------------------------------------------------
    # REPORT SECTIONS
    # ---------------------------------------------------------

    st.markdown("## 📚 Report Sections")

    for index, section in enumerate(sections, start=1):

        st.markdown(
            f"""
            <div class="info-card">
                <h3>{index}. {section}</h3>
                <p>
                    This section will contain the corresponding
                    AI-generated research analysis.
                </p>
            </div>
            """,
            unsafe_allow_html=True
        )

    # ---------------------------------------------------------
    # LITERATURE REVIEW PREVIEW
    # ---------------------------------------------------------

    st.markdown("## 📝 Literature Review Preview")

    introduction = review.get(
        "introduction",
        "No literature review available."
    )

    st.markdown(
        f"""
        <div class="info-card">
            <h3>Introduction</h3>
            <p>{introduction}</p>
        </div>
        """,
        unsafe_allow_html=True
    )

    # ---------------------------------------------------------
    # EXPORT
    # ---------------------------------------------------------

    st.markdown("## 📥 Export Report")

    export_col1, export_col2 = st.columns(2)

    with export_col1:
        if st.button(
            "📄 Download PDF Report",
            use_container_width=True
        ):
            st.info(
                "Demo Mode: PDF generation will be enabled "
                "after backend integration."
            )

    with export_col2:
        if st.button(
            "📝 Download Word Report",
            use_container_width=True
        ):
            st.info(
                "Demo Mode: Word report generation will be enabled "
                "after backend integration."
            )

    # ---------------------------------------------------------
    # FINAL STATUS
    # ---------------------------------------------------------

    st.markdown(
        """
        <div class="status-card">
            <div>
                <strong>Report Generation</strong><br>
                <span>
                    Frontend report interface is ready.
                    Backend-generated reports will be connected later.
                </span>
            </div>

            <div class="status-pill">
                ● FRONTEND READY
            </div>
        </div>
        """,
        unsafe_allow_html=True
    )